"""
Mock Data Provider — realistic sample data mirroring real API schemas.

WHY MOCKS: The container's network egress is restricted to specific domains.
Polymarket (gamma-api.polymarket.com) and Kalshi (api.elections.kalshi.com)
are not in the allowlist. The adapters are written against the real APIs
and will work in any unrestricted environment.

The mock data below mirrors the exact JSON structures returned by each API,
including intentional cross-venue overlaps for demonstrating equivalence detection.
"""

from datetime import datetime, timezone, timedelta

# Current time for realistic timestamps
NOW = datetime.now(timezone.utc)
TOMORROW = NOW + timedelta(days=1)
NEXT_WEEK = NOW + timedelta(days=7)
NEXT_MONTH = NOW + timedelta(days=30)
END_OF_YEAR = datetime(2026, 12, 31, tzinfo=timezone.utc)


# ============================================================
# POLYMARKET MOCK DATA (mirrors gamma-api.polymarket.com/events)
# ============================================================

POLYMARKET_EVENTS = [
    {
        "id": "pm-evt-1001",
        "title": "Fed Interest Rate Decision - March 2026",
        "slug": "fed-rate-decision-march-2026",
        "tags": [{"label": "Economics"}, {"label": "Federal Reserve"}],
        "markets": [
            {
                "id": "pm-mkt-2001",
                "conditionId": "0xabc123",
                "question": "Will the Fed cut interest rates at the March 2026 meeting?",
                "description": "This market resolves to Yes if the Federal Open Market Committee (FOMC) announces a reduction in the federal funds rate at its March 2026 meeting.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.35", "0.65"]',
                "volume": "2450000",
                "active": True,
                "closed": False,
                "endDate": (NOW + timedelta(days=5)).isoformat(),
            },
        ],
    },
    {
        "id": "pm-evt-1002",
        "title": "Bitcoin Price Milestones",
        "slug": "bitcoin-price-milestones",
        "tags": [{"label": "Crypto"}, {"label": "Bitcoin"}],
        "markets": [
            {
                "id": "pm-mkt-2002",
                "conditionId": "0xdef456",
                "question": "Will Bitcoin exceed $150,000 by end of 2026?",
                "description": "Resolves Yes if BTC/USD trades above $150,000 on any major exchange before December 31, 2026.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.28", "0.72"]',
                "volume": "8900000",
                "active": True,
                "closed": False,
                "endDate": END_OF_YEAR.isoformat(),
            },
            {
                "id": "pm-mkt-2003",
                "conditionId": "0xghi789",
                "question": "Will Bitcoin exceed $200,000 by end of 2026?",
                "description": "Resolves Yes if BTC/USD trades above $200,000 on any major exchange before December 31, 2026.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.08", "0.92"]',
                "volume": "3200000",
                "active": True,
                "closed": False,
                "endDate": END_OF_YEAR.isoformat(),
            },
        ],
    },
    {
        "id": "pm-evt-1003",
        "title": "2026 US Midterm Elections",
        "slug": "2026-us-midterm-elections",
        "tags": [{"label": "Politics"}, {"label": "Elections"}],
        "markets": [
            {
                "id": "pm-mkt-2004",
                "conditionId": "0xjkl012",
                "question": "Will Republicans win the House in 2026 midterms?",
                "description": "Resolves Yes if the Republican Party wins a majority of seats in the US House of Representatives in the 2026 midterm elections.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.52", "0.48"]',
                "volume": "5600000",
                "active": True,
                "closed": False,
                "endDate": datetime(2026, 11, 5, tzinfo=timezone.utc).isoformat(),
            },
            {
                "id": "pm-mkt-2005",
                "conditionId": "0xmno345",
                "question": "Will Democrats win the Senate in 2026 midterms?",
                "description": "Resolves Yes if the Democratic Party wins a majority (or 50 seats + VP tiebreaker) in the US Senate.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.41", "0.59"]',
                "volume": "4100000",
                "active": True,
                "closed": False,
                "endDate": datetime(2026, 11, 5, tzinfo=timezone.utc).isoformat(),
            },
        ],
    },
    {
        "id": "pm-evt-1004",
        "title": "US Recession 2026",
        "slug": "us-recession-2026",
        "tags": [{"label": "Economics"}, {"label": "GDP"}],
        "markets": [
            {
                "id": "pm-mkt-2006",
                "conditionId": "0xpqr678",
                "question": "Will the US enter a recession in 2026?",
                "description": "Resolves Yes if the NBER declares a US recession with a start date in 2026, or if two consecutive quarters of negative GDP growth occur in 2026.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.22", "0.78"]',
                "volume": "6700000",
                "active": True,
                "closed": False,
                "endDate": END_OF_YEAR.isoformat(),
            },
        ],
    },
    {
        "id": "pm-evt-1005",
        "title": "Ethereum Price",
        "slug": "ethereum-price-2026",
        "tags": [{"label": "Crypto"}, {"label": "Ethereum"}],
        "markets": [
            {
                "id": "pm-mkt-2007",
                "conditionId": "0xstu901",
                "question": "Will Ethereum exceed $10,000 by end of 2026?",
                "description": "Resolves Yes if ETH/USD trades above $10,000 on any major exchange before December 31, 2026.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.15", "0.85"]',
                "volume": "2100000",
                "active": True,
                "closed": False,
                "endDate": END_OF_YEAR.isoformat(),
            },
        ],
    },
    {
        "id": "pm-evt-1006",
        "title": "CPI March 2026",
        "slug": "cpi-march-2026",
        "tags": [{"label": "Economics"}, {"label": "Inflation"}],
        "markets": [
            {
                "id": "pm-mkt-2008",
                "conditionId": "0xvwx234",
                "question": "Will March 2026 CPI come in above 3.0%?",
                "description": "Resolves Yes if the Bureau of Labor Statistics reports year-over-year CPI above 3.0% for March 2026.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.40", "0.60"]',
                "volume": "1800000",
                "active": True,
                "closed": False,
                "endDate": (NOW + timedelta(days=20)).isoformat(),
            },
        ],
    },
    {
        "id": "pm-evt-1007",
        "title": "NBA Finals 2026",
        "slug": "nba-finals-2026",
        "tags": [{"label": "Sports"}, {"label": "NBA"}],
        "markets": [
            {
                "id": "pm-mkt-2009",
                "conditionId": "0xyza567",
                "question": "Will the Boston Celtics win the 2026 NBA Finals?",
                "description": "Resolves Yes if the Boston Celtics win the 2025-2026 NBA Championship.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.18", "0.82"]',
                "volume": "3400000",
                "active": True,
                "closed": False,
                "endDate": datetime(2026, 6, 30, tzinfo=timezone.utc).isoformat(),
            },
        ],
    },
    {
        "id": "pm-evt-1008",
        "title": "AI Regulation",
        "slug": "ai-regulation-2026",
        "tags": [{"label": "Politics"}, {"label": "Technology"}],
        "markets": [
            {
                "id": "pm-mkt-2010",
                "conditionId": "0xbcd890",
                "question": "Will Congress pass federal AI regulation by end of 2026?",
                "description": "Resolves Yes if the US Congress passes a federal law specifically regulating artificial intelligence by December 31, 2026.",
                "outcomes": '["Yes", "No"]',
                "outcomePrices": '["0.12", "0.88"]',
                "volume": "1200000",
                "active": True,
                "closed": False,
                "endDate": END_OF_YEAR.isoformat(),
            },
        ],
    },
]


# ============================================================
# KALSHI MOCK DATA (mirrors api.elections.kalshi.com/trade-api/v2/markets)
# ============================================================

KALSHI_MARKETS = [
    {
        "ticker": "KXFED-26MAR-T5.00",
        "event_ticker": "KXFED-26MAR",
        "series_ticker": "KXFED",
        "market_type": "binary",
        "title": "Fed to cut rates at March 2026 meeting?",
        "subtitle": "Federal funds rate reduction",
        "yes_sub_title": "Yes, cut",
        "no_sub_title": "No cut",
        "status": "open",
        "yes_ask_dollars": "0.3800",
        "no_ask_dollars": "0.6500",
        "last_price_dollars": "0.3700",
        "volume_fp": "1850000",
        "open_interest_fp": "450000",
        "close_time": (NOW + timedelta(days=5)).isoformat(),
        "expiration_time": (NOW + timedelta(days=6)).isoformat(),
    },
    {
        "ticker": "KXBTC-26DEC-T150000",
        "event_ticker": "KXBTC-26DEC",
        "series_ticker": "KXBTC",
        "market_type": "binary",
        "title": "Bitcoin above $150,000 on December 31?",
        "subtitle": "BTC/USD year-end price",
        "yes_sub_title": "Yes, above",
        "no_sub_title": "No, at or below",
        "status": "open",
        "yes_ask_dollars": "0.3200",
        "no_ask_dollars": "0.7100",
        "last_price_dollars": "0.3100",
        "volume_fp": "5200000",
        "open_interest_fp": "1200000",
        "close_time": END_OF_YEAR.isoformat(),
        "expiration_time": END_OF_YEAR.isoformat(),
    },
    {
        "ticker": "KXBTC-26DEC-T200000",
        "event_ticker": "KXBTC-26DEC",
        "series_ticker": "KXBTC",
        "market_type": "binary",
        "title": "Bitcoin above $200,000 on December 31?",
        "subtitle": "BTC/USD year-end price",
        "yes_sub_title": "Yes, above",
        "no_sub_title": "No, at or below",
        "status": "open",
        "yes_ask_dollars": "0.1100",
        "no_ask_dollars": "0.9200",
        "last_price_dollars": "0.1000",
        "volume_fp": "2800000",
        "open_interest_fp": "800000",
        "close_time": END_OF_YEAR.isoformat(),
        "expiration_time": END_OF_YEAR.isoformat(),
    },
    {
        "ticker": "KXHOUSE-26NOV",
        "event_ticker": "KXELECT-26NOV",
        "series_ticker": "KXHOUSE",
        "market_type": "binary",
        "title": "Republicans to win House majority in 2026?",
        "subtitle": "2026 midterm elections",
        "yes_sub_title": "Republican majority",
        "no_sub_title": "No Republican majority",
        "status": "open",
        "yes_ask_dollars": "0.5500",
        "no_ask_dollars": "0.4800",
        "last_price_dollars": "0.5400",
        "volume_fp": "4200000",
        "open_interest_fp": "980000",
        "close_time": datetime(2026, 11, 5, tzinfo=timezone.utc).isoformat(),
        "expiration_time": datetime(2026, 11, 10, tzinfo=timezone.utc).isoformat(),
    },
    {
        "ticker": "KXSENATE-26NOV",
        "event_ticker": "KXELECT-26NOV",
        "series_ticker": "KXSENATE",
        "market_type": "binary",
        "title": "Democrats to win Senate majority in 2026?",
        "subtitle": "2026 midterm elections",
        "yes_sub_title": "Democratic majority",
        "no_sub_title": "No Democratic majority",
        "status": "open",
        "yes_ask_dollars": "0.4400",
        "no_ask_dollars": "0.5900",
        "last_price_dollars": "0.4300",
        "volume_fp": "3800000",
        "open_interest_fp": "870000",
        "close_time": datetime(2026, 11, 5, tzinfo=timezone.utc).isoformat(),
        "expiration_time": datetime(2026, 11, 10, tzinfo=timezone.utc).isoformat(),
    },
    {
        "ticker": "KXGDP-26-REC",
        "event_ticker": "KXGDP-26",
        "series_ticker": "KXGDP",
        "market_type": "binary",
        "title": "US recession in 2026?",
        "subtitle": "NBER-defined recession beginning in 2026",
        "yes_sub_title": "Recession declared",
        "no_sub_title": "No recession",
        "status": "open",
        "yes_ask_dollars": "0.2500",
        "no_ask_dollars": "0.7800",
        "last_price_dollars": "0.2400",
        "volume_fp": "4900000",
        "open_interest_fp": "1100000",
        "close_time": END_OF_YEAR.isoformat(),
        "expiration_time": END_OF_YEAR.isoformat(),
    },
    {
        "ticker": "KXCPI-26MAR-T3.0",
        "event_ticker": "KXCPI-26MAR",
        "series_ticker": "KXCPI",
        "market_type": "binary",
        "title": "March 2026 CPI above 3.0%?",
        "subtitle": "Year-over-year CPI inflation",
        "yes_sub_title": "Above 3.0%",
        "no_sub_title": "At or below 3.0%",
        "status": "open",
        "yes_ask_dollars": "0.4300",
        "no_ask_dollars": "0.6000",
        "last_price_dollars": "0.4200",
        "volume_fp": "1500000",
        "open_interest_fp": "350000",
        "close_time": (NOW + timedelta(days=20)).isoformat(),
        "expiration_time": (NOW + timedelta(days=21)).isoformat(),
    },
    {
        "ticker": "KXNBA-26FINALS-BOS",
        "event_ticker": "KXNBA-26FINALS",
        "series_ticker": "KXNBA",
        "market_type": "binary",
        "title": "Celtics to win 2026 NBA Championship?",
        "subtitle": "2025-26 NBA Finals",
        "yes_sub_title": "Celtics win",
        "no_sub_title": "Celtics don't win",
        "status": "open",
        "yes_ask_dollars": "0.2100",
        "no_ask_dollars": "0.8200",
        "last_price_dollars": "0.2000",
        "volume_fp": "2700000",
        "open_interest_fp": "650000",
        "close_time": datetime(2026, 6, 30, tzinfo=timezone.utc).isoformat(),
        "expiration_time": datetime(2026, 7, 5, tzinfo=timezone.utc).isoformat(),
    },
    {
        "ticker": "KXETH-26DEC-T10000",
        "event_ticker": "KXETH-26DEC",
        "series_ticker": "KXETH",
        "market_type": "binary",
        "title": "Ethereum above $10,000 on December 31?",
        "subtitle": "ETH/USD year-end price",
        "yes_sub_title": "Yes, above $10K",
        "no_sub_title": "No, at or below",
        "status": "open",
        "yes_ask_dollars": "0.1800",
        "no_ask_dollars": "0.8500",
        "last_price_dollars": "0.1700",
        "volume_fp": "1600000",
        "open_interest_fp": "400000",
        "close_time": END_OF_YEAR.isoformat(),
        "expiration_time": END_OF_YEAR.isoformat(),
    },
    {
        "ticker": "KXPRES-AI-REG-26",
        "event_ticker": "KXPRES-AI-26",
        "series_ticker": "KXPRES",
        "market_type": "binary",
        "title": "Federal AI regulation law passed by end of 2026?",
        "subtitle": "Congressional action on AI",
        "yes_sub_title": "Law passed",
        "no_sub_title": "No law passed",
        "status": "open",
        "yes_ask_dollars": "0.1500",
        "no_ask_dollars": "0.8800",
        "last_price_dollars": "0.1400",
        "volume_fp": "900000",
        "open_interest_fp": "220000",
        "close_time": END_OF_YEAR.isoformat(),
        "expiration_time": END_OF_YEAR.isoformat(),
    },
]
